/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_cassandra_index_sai_disk_pgm_PGMIndex */

#ifndef _Included_org_apache_cassandra_index_sai_disk_pgm_PGMIndex
#define _Included_org_apache_cassandra_index_sai_disk_pgm_PGMIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_cassandra_index_sai_disk_pgm_PGMIndex
 * Method:    create
 * Signature: ([JLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_apache_cassandra_index_sai_disk_pgm_PGMIndex_create
  (JNIEnv *, jobject, jlongArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
